export enum TextTypes {
    TITLE_BOLD = 'TITLE', //24PX
    TITLE_REGULAR = 'TITLE_REGULAR',
    TITLE_LIGHT = 'TITLE_LIGHT',
    PARAGRAPH_BOLD = 'PARAGRAPH_BOLD',//20PX
    PARAGRAPH_REGULAR = 'PARAGRAPH_REGULAR',
    PARAGRAPH_LIGHT = 'PARAGRAPH_LIGHT',
    SUB_TITLE_BOLD = 'SUBTITLE_BOLD',//14PX
    SUB_TITLE_REGULAR = 'SUBTITLE_REGULAR',
    SUB_TITLE_LIGHT = 'SUBTITLE_LIGHT',
    PARAGRAPH_SMALL_BOLD = 'PARAGRAPH_SMALL_BOLD',//10PX
    PARAGRAPH_SMALL_REGULAR = 'PARAGRAPH_SMALL_REGULAR',
    PARAGRAPH_SMALL_LIGHT = 'PARAGRAPH_SMALL_LIGHT',
    BUTTON_BOLD = 'BUTTON_BOLD',//18PX
    BUTTON_REGULAR = 'BUTTON_REGULAR',
    BUTTON_LIGHT = 'BUTTON_LIGHT',
}